meal_plans/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from meal_plans.views import (
    MealPlanCreateView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plans_detail"),
    path("new/", MealPlanCreateView.as_view(), name="meal_plans_new"),
    path(
        "<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plans_edit"
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagUpdateView,
    TagDetailView,
    TagDeleteView,
    TagCreateView,
)


urlpatterns = [
    path("", TagListView.as_view(), name="tag_list"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(auto_now_add=False)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", blank=True)

meal_plans/views.py
from sre_constants import SUCCESS
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from meal_plans.models import MealPlan

# Create your views here.


class MealPlanCreateView(CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class MealPlanListView(ListView):
    paginate = 3
    model = MealPlan
    template_name = "meal_plans/list.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"


class MealPlanDeleteView(DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
  <main class="meal_plans-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Delete</button>
      </div>
    </form>
  </main>
  {% endif %}
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdownify %}
{% block content %}
{% if user.is_authenticated %}
  <main class="meal_plans-detail">
    <div>
      <a href="{% url 'meal_plans_edit' mealplan.pk %}">Edit</a>
      <a href="{% url 'meal_plans_delete' mealplan.pk %}">Delete</a>
    </div>
    {% if recipe.image %}
      <img src="{{ recipe.image }}" class="pull-right">
    {% endif %}
    <h1>{{ mealplan.name }}</h1>
    <p>
      Created on {{ mealplan.created }} |
      Updated on {{ mealplan.updated }}
    </p>
    <p>Tags: {% for meal in recipe.meal_plans.all %}{{ meal_plans.word }} {% endfor %}</p>
    {{ recipe.description | markdownify }}
    <h2>Ingredients</h2>
    <table>
      <thead>
        <tr>
          <th colspan="2">Amount</th>
          <th>Food item</th>
        </tr>
      </thead>
      <tbody>
        {% for ingredient in recipe.ingredients.all %}
          <tr>
            <td>{{ ingredient.amount }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <h2>Steps</h2>
    <ol>
      {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
      {% endfor %}
    </ol>
  </main>
{% endif %}
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="meal_plans-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'paginate.html' %}


{% block content %}
  <div>
    <h2> <a href="{% url 'meal_plans_new' %}">New Meal Plan</a>
    </h2>
  </div>
  <main class="recipe-grid">

    {% for mealplan in mealplan_list %}
      <div class="meal_plan-card">
        <h2 class="meal_plan-card-title">
          <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
        {% for meals in meal_plans.meal_plans.all %}
          <p>
            <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
          </p>
        {% endfor %}
      </div>
    {% empty %}
      <div>
        <h1>No meal plans yet!</h1>
        <p>
          Would you like to
          <a href="{% url 'meal_plans_new' %}">create</a>
          one?
        </p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="meal_plans-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}